### ISSUE TITLE
cookiecutter model

### ISSUE THREAD

**Issue by SilvyPuzzlewell** [oarepo/cookiecutter-model#1]
## Tasks

- [ ] pinned main
- [ ] branch
- [x] readme documentation
- [ ] dev documentation
- [x] support for files
- [x] support for requests
- [x] support for expandable fields
- [x] support for custom fields
- [x] support for relations  

## Required for

- [x] NR
- [x] MOSBRI

**Comment by mesemus** [comment]
moved directly to oarepo-cli
